[book]
authors = ["Wolf McNally"]
language = "en"
multilingual = false
src = "src"
title = "The CBOR, dCBOR, and Gordian Envelope Book"

[output.html.playground]
runnable = false

[preprocessor.dcbor-shiki]
